name: marineprojects_wps
channels:
  - conda-forge
  - defaults
dependencies:
  - flask=3.0.3
  - geoserver-rest=2.7.0
  - pandas=2.2.2
  - pip=24.0
  - python=3.12.4
  - sqlalchemy=2.0.30
  - pip:
      - psycopg2-binary==2.9.9
      - pywps==4.6.0

