name: marineprojects_wps
channels:
  - conda-forge
dependencies:
  - flask=3
  - geoserver-rest=2
  - pandas=2
  - pip=24
  - python=3
  - sqlalchemy=2
  - geoalchemy2=
  - geopandas=
  - fiona=
  - boto3=
  - pip:
      - psycopg2-binary>=2
      - pywps>=4

